#! /bin/bash

# TODO: CAMBIAR CUANDO PUEDA TRAERLOS
BINDIR=`pwd`
LOGFILE=log

#### Inicialización de log

echo 'Comando InicioX Inicio de Ejecución' >> ${LOGFILE}

#### Verificación de instalación
## Verificación de comandos
comandos=('InicioX' 'DetectaX' 'foo' 'bar')
comandosFaltantes=()
comandosNoEjecutables=()
comandosOk=()

for c in ${comandos[@]}; do
	f="${BINDIR}/$c"
	a=($c)
	if [ ! -f $f ]; then
		comandosFaltantes+=$a
	elif [ ! -x $f ]; then
		comandosNoEjecutables+=$a
	else
		comandosOK+=$a
	fi
done
## Reporte de situación
echo "Comandos registrados:" >&2
echo ${comandos[@]} >&2
if [ "${comandosNoEjecutables}x" != 'x' ]; then
	echo "Comandos no ejecutables:" >&2
	echo ${comandosNoEjecutables[@]} >&2
fi
# Comandos faltantes
if [ "${comandosFaltantes}x" != 'x' ]; then
	echo "Faltan los siguientes comandos, no se puede continuar:" >&2
	echo ${comandosFaltantes[@]} >&2
	exit 1
# Arreglo de permisos
elif [ "${comandosNoEjecutables}x" != 'x' ]; then
	echo "Desea hacerlos ejecutables? (s/N)" >&2
	read ans
	if [ "${ans}x" == sx -o "${ans}x" == Sx ]; then
		echo Cambiando permisos... >&2
		bad=()
		for c in ${comandosNoEjecutables[@]}; do
			f="${BINDIR}/$c"
			if chmod gu+x $f 2>/dev/null; then
				echo OK: $c >&2
			else
				echo KO: $c >&2
				bad+=($c)
			fi
		done
		if [ "${bad}x" != "x" ]; then
			echo "No se pueden hacer ejecutables los siguientes comandos:" >&2
			echo ${bad[@]} >&2
			exit 3
		fi
	else
		exit 2
	fi
fi

####TODO: Verificar archivos de configuración

####TODO: Fallar si el entorno está inicializado

#### Exporto variables de entorno
PATH+="${BINDIR}:"
export PATH
#TODO: otros directorios

#### TODO: CANLOOP, TESPERA
#### Ejecución de DetectaX
echo "Desea efectuar la activación de DetectaX? (S/n)"
read ans
if [ "${ans}x" == sx -o "${ans}x" == Sx ]; then
	DetectaX
fi

